### ISSUE TITLE
I didn't find all textures.Please help me

### ISSUE THREAD

**Issue by RDQpixelatedMan** [y0lopix/pixel-gun-3d-assets#3]
I checked all the textures in the file, but could not find the textures belonging to the game maps.Could you fix it or help me? I really need texture of campaign maps!:(

**Comment by y0lopix** [comment]
Which textures from campaign maps do you need exactly? Some of them may be missing because I haven't currently pushed the latest assets.

**Comment by RDQpixelatedMan** [comment]
I need campaign files 1 and 2. The problem is that they were in the game almost from the beginning.

**Comment by y0lopix** [comment]
All campaign textures are in the [Texture2D Folder](../tree/master/Extracted/Texture2D). Campaign maps are often named LevelX (with a number in place of X)
For example, Level4 is Hospital and Level9 is Slender Forest.

**Comment by RDQpixelatedMan** [comment]
I know this, but I just did not find these files. There is simply no such thing! Both in the most downloaded file and on the site!Maybe I'm doing something wrong, but I was looking for them in "Texture2D"
There are only enemies of levels :(
(Texture2D/Enemy_level2 or others)

**Comment by RDQpixelatedMan** [comment]
are you on social networks? Twitter, facebook or something else. I think it will be easier to finish this problem(Sorry for my bad English)

**Comment by y0lopix** [comment]
My Twitter is [@y0lopix](http://twitter.com/y0lopix)

**Comment by RDQpixelatedMan** [comment]
Maybe I'm doing something wrong, but I was looking for them in "Texture2D"
There are only enemies of levels :(
(Texture2D/Enemy_level2 or others)

**Comment by RDQpixelatedMan** [comment]
...

**Comment by y0lopix** [comment]
> are you on social networks? Twitter, facebook or something else. I think it will be easier to finish this problem(Sorry for my bad English)

I replied you on Twitter about this problem, go take a look at your DMs
